In [132]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import keras
import tensorflow as tf
import pandas as pd
import datetime
import keras.backend as K
K.clear_session()
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout


First let's import keras and some other libraries

In [133]:
 data = pd.read_csv("m_stroman_pitches_v3.csv")

let's load the pitches. above are 3045 pitches, that marcus stroman threw in sequence from 2019

In [134]:
df = pd.DataFrame(data)

pitches = df['pitch_type']
pitches = pd.get_dummies(pitches) #get a one hot encoding for pitches
p_enc = pitches.to_numpy()

del df['pitch_type'] #don't need pitch type anymore

In [135]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["stand"] = le.fit_transform(df["stand"])
#df["prev_type"] = le.fit_transform(df["prev_type"])

ty = pd.get_dummies(df['prev_type'])
df = df.drop('prev_type',axis = 1)
# Join the encoded df
df = df.join(ty)
#df["prev_pitch"] = le.fit_transform(df["prev_pitch"])

prevs = pd.get_dummies(df['prev_pitch'])
df = df.drop('prev_pitch',axis = 1)
# Join the encoded df
df = df.join(prevs)
variables = df.to_numpy()
print(variables)

[[ 1  2  0  0  0  1  0  1  0  0  0  1  0]
 [ 1  3  0  0  0  1  0  1  0  0  0  1  0]
 [ 1  0  0  1  0  1  0  1  0  0  0  1  0]
 [ 1  0  0  1  1  1  0  0  0  1  0  1  0]
 [ 1  0  1  1  1  1  0  0  1  0  0  1  0]
 [ 1  1  1  1  1  1  0  1  0  0  1  0  0]
 [ 1  2  1  1  1  1  0  1  0  0  0  1  0]
 [ 0  0  0  0  0  2  0  0  0  1  0  1  0]
 [ 0  0  1  0  0  2  0  0  1  0  1  0  0]
 [ 0  0  2  0  0  2  0  0  1  0  0  1  0]
 [ 0  0  0  0  1  2  0  0  0  1  0  1  0]
 [ 0  1  0  0  1  2  0  1  0  0  0  1  0]
 [ 0  2  0  0  1  2  0  1  0  0  1  0  0]
 [ 0  3  0  0  1  2  0  1  0  0  0  0  1]
 [ 0  3  1  0  1  2  0  0  1  0  0  1  0]
 [ 0  0  0  1  1  2  0  1  0  0  0  1  0]
 [ 0  0  1  1  1  2  0  0  1  0  1  0  0]
 [ 0  0  2  1  1  2  0  0  1  0  1  0  0]
 [ 0  1  2  0  2  2  0  1  0  0  1  0  0]
 [ 0  2  2  0  2  2  0  1  0  0  0  1  0]
 [ 1  0  0  0  0  3  0  0  1  0  1  0  0]
 [ 1  0  1  0  0  3  0  0  1  0  1  0  0]
 [ 1  1  1  0  0  3  0  1  0  0  1  0  0]
 [ 1  2  1  0  0  3  0  1  0  0  0

In [136]:
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split( 
    variables, p_enc, test_size=0.2)

In [137]:
print(trainX.shape)
print(trainY.shape)

(2435, 13)
(2435, 3)


In [143]:
model = Sequential()
from keras.optimizers import SGD
model.add(Dense(8, activation = 'relu', input_dim = 13))
model.add(Dense(3, activation = 'softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(trainX, trainY, epochs = 100,
            batch_size = 64)

Epoch 1/100
2435/2435 [==============================] - 0s 31us/step - loss: 0.9782 - accuracy: 0.4940
Epoch 2/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8783 - accuracy: 0.5396
Epoch 3/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8684 - accuracy: 0.5396
Epoch 4/100
2435/2435 [==============================] - 0s 13us/step - loss: 0.8588 - accuracy: 0.5441
Epoch 5/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8589 - accuracy: 0.5425
Epoch 6/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8483 - accuracy: 0.5495
Epoch 7/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8439 - accuracy: 0.5630
Epoch 8/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8430 - accuracy: 0.5647
Epoch 9/100
2435/2435 [==============================] - 0s 12us/step - loss: 0.8391 - accuracy: 0.5774
Epoch 10/100
2435/2435 [==============================] - 0s 12u

2435/2435 [==============================] - 0s 12us/step - loss: 0.8105 - accuracy: 0.5893
Epoch 78/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8091 - accuracy: 0.5906
Epoch 79/100
2435/2435 [==============================] - 0s 12us/step - loss: 0.8109 - accuracy: 0.5971
Epoch 80/100
2435/2435 [==============================] - 0s 12us/step - loss: 0.8097 - accuracy: 0.5914
Epoch 81/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8098 - accuracy: 0.6004
Epoch 82/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8107 - accuracy: 0.5951
Epoch 83/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8090 - accuracy: 0.5926
Epoch 84/100
2435/2435 [==============================] - 0s 12us/step - loss: 0.8149 - accuracy: 0.5992
Epoch 85/100
2435/2435 [==============================] - 0s 11us/step - loss: 0.8094 - accuracy: 0.5930
Epoch 86/100
2435/2435 [==============================] - 0s 11us/st

In [144]:
score = model.evaluate(testX, testY, batch_size = 32)
print("Test Accuracy: "+"{:.2%}".format(score[1]))

609/609 [==============================] - 0s 56us/step
Test Accuracy: 61.25%


In [145]:
f = open("file.txt", "a")
import sys
np.set_printoptions(threshold=sys.maxsize)
f.write(np.array2string(model.predict(testX)))
f.close()